[tool.poetry]
name = "bjj-partner-assessment"
version = "0.1.0"
description = "BJJ Partner Assessment Tool"
authors = ["jelaludo"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "2.3.3"
python-dotenv = "1.0.0"
gunicorn = "21.2.0"
Werkzeug = "3.0.1"
click = "^8.0.0"
itsdangerous = "^2.0"
Jinja2 = "^3.0"
MarkupSafe = "^2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"