services:
  - type: web
    name: bjj-partner-assessment
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: .
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: ADMIN_MODE
        value: true