services:
  - type: web
    name: bjj-partner-assessment
    runtime: python
    rootDirectory: .
    buildCommand: ls -la && pwd && pip install poetry && poetry install
    startCommand: poetry run gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: ADMIN_MODE
        value: "true" 